[package]
name = "clamav-client"
version = "0.2.2"
authors = ["Thorsten Blum"]
edition = "2021"
repository = "https://github.com/toblux/rust-clamav-client"
description = "ClamAV client library"
readme = "README.md"
license = "MIT"
keywords = ["clamav", "clamd", "anitvirus"]

[dependencies]
tokio = { version = "1.34.0", features = ["fs", "io-std", "io-util", "macros", "net", "rt"], optional = true }

[features]
asynch = ["dep:tokio"]