[package]
name = "clamav-client"
version = "0.1.3"
authors = ["Thorsten Blum"]
edition = "2021"
repository = "https://github.com/toblux/rust-clamav-client"
description = "ClamAV client library"
readme = "README.md"
license = "MIT"
keywords = ["clamav", "clamd", "anitvirus"]
